<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductErzapSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Data Source (Data Lama)
        $oldData = [
            [
                'id' => 1,
                'kode' => '2J3II190252',
                'nama' => 'ACC SAMSUNG BOOKCOVER KEYBOARD TAB S9',
                'slug' => 'acc-samsung-bookcover-keyboard-tab-s9',
                'barcode' => '786868071578',
                'harga_jual' => 2499000.00,
                'is_active' => 1,
                'is_jasa' => 0,
                'meta_keyword' => 'ACC SAMSUNG BOOKCOVER KEYBOARD TAB S9 BLACK - BLAC...',
                'meta_description' => 'ACC SAMSUNG BOOKCOVER KEYBOARD TAB S9 BLACK - BLAC...',
                'harga_diskon' => null,
                'deskripsi_produk' => null,
                'berat' => 1,
                'berat_pengiriman' => 1,
                'overview' => null,
                'is_paket' => 0,
                'harga_jual_web' => null,
                'harga_diskon_web' => null,
                'nama_web' => null,
                'kode_ref' => null,
                'produk_nama' => 'ACC SAMSUNG BOOKCOVER KEYBOARD TAB S9 - BLACK',
                'available_stok' => 0,
                'merek_kode' => '1GA827285',
                'merek_nama' => 'SAMSUNG',
                'kategori_kode' => null,
                'kategori_nama' => null,
                'sub_kategori_kode' => null,
                'sub_kategori_nama' => null,
                'produk_satuan_kode' => '1100K2728',
                'produk_satuan_nama' => 'Unit',
                'produk_warna_kode' => '1ZCJP2728',
                'produk_warna_nama' => 'BLACK',
                'produk_ukuran_kode' => null,
                'produk_ukuran_nama' => null,
                'created_at' => Carbon::parse('2025-07-08 06:19:31'),
                'updated_at' => Carbon::parse('2025-07-08 06:19:31'),
            ],
            [
                'id' => 2,
                'kode' => '2IX78292422',
                'nama' => 'ACC CASE SAMSUNG S24 SMART VIEW WALLET',
                'slug' => 'acc-case-samsung-s24-smart-view-wallet',
                'barcode' => '1745918575390',
                'harga_jual' => 0.00,
                'is_active' => 1,
                'is_jasa' => 0,
                'meta_keyword' => 'ACC CASE SAMSUNG S24 SMART VIEW WALLET - GREEN',
                'meta_description' => 'ACC CASE SAMSUNG S24 SMART VIEW WALLET - GREEN',
                'harga_diskon' => null,
                'deskripsi_produk' => null,
                'berat' => 1,
                'berat_pengiriman' => 1,
                'overview' => null,
                'is_paket' => 0,
                'harga_jual_web' => null,
                'harga_diskon_web' => null,
                'nama_web' => null,
                'kode_ref' => null,
                'produk_nama' => 'ACC CASE SAMSUNG S24 SMART VIEW WALLET - GREEN',
                'available_stok' => 5,
                'merek_kode' => '1GA827285',
                'merek_nama' => 'SAMSUNG',
                'kategori_kode' => null,
                'kategori_nama' => null,
                'sub_kategori_kode' => null,
                'sub_kategori_nama' => null,
                'produk_satuan_kode' => '1LEGN2728',
                'produk_satuan_nama' => 'Pcs',
                'produk_warna_kode' => '15O2Y2728',
                'produk_warna_nama' => 'GREEN',
                'produk_ukuran_kode' => null,
                'produk_ukuran_nama' => null,
                'created_at' => Carbon::parse('2025-07-08 06:19:31'),
                'updated_at' => Carbon::parse('2025-07-08 06:19:31'),
            ],
            [
                'id' => 3,
                'kode' => '2ER1X030626',
                'nama' => 'Tecno Spark 30C 8/256GB',
                'slug' => 'tecno-spark-30c-8256gb',
                'barcode' => '1738580728765',
                'harga_jual' => 1699000.00,
                'is_active' => 1,
                'is_jasa' => 0,
                'meta_keyword' => 'Tecno Spark 30C 8/256GB - WHITE',
                'meta_description' => 'Tecno Spark 30C 8/256GB - WHITE',
                'harga_diskon' => null,
                'deskripsi_produk' => null,
                'berat' => 1,
                'berat_pengiriman' => 1,
                'overview' => null,
                'is_paket' => 0,
                'harga_jual_web' => null,
                'harga_diskon_web' => null,
                'nama_web' => null,
                'kode_ref' => null,
                'produk_nama' => 'Tecno Spark 30C 8/256GB - WHITE',
                'available_stok' => 8,
                'merek_kode' => '7832GWM22',
                'merek_nama' => 'TECNO',
                'kategori_kode' => '12Z3J2847',
                'kategori_nama' => 'HP BARU',
                'sub_kategori_kode' => '1T6AE1905',
                'sub_kategori_nama' => 'HANDPHONE',
                'produk_satuan_kode' => '1100K2728',
                'produk_satuan_nama' => 'Unit',
                'produk_warna_kode' => '1PGXA2728',
                'produk_warna_nama' => 'WHITE',
                'produk_ukuran_kode' => null,
                'produk_ukuran_nama' => null,
                'created_at' => Carbon::parse('2025-07-08 06:19:31'),
                'updated_at' => Carbon::parse('2025-07-08 06:19:31'),
            ],
            [
                'id' => 4,
                'kode' => '27AD8115320',
                'nama' => 'HP SAMSUNG GALAXY Z FLIP 6 F741B 12/256GB',
                'slug' => 'hp-samsung-galaxy-z-flip-6-f741b-12256gb',
                'barcode' => '1720705395396',
                'harga_jual' => 17499000.00,
                'is_active' => 1,
                'is_jasa' => 0,
                'meta_keyword' => 'HP SAMSUNG GALAXY Z FLIP 6 12/256GB - MINT',
                'meta_description' => 'HP SAMSUNG GALAXY Z FLIP 6 12/256GB - MINT',
                'harga_diskon' => null,
                'deskripsi_produk' => null,
                'berat' => 1,
                'berat_pengiriman' => 1,
                'overview' => null,
                'is_paket' => 0,
                'harga_jual_web' => null,
                'harga_diskon_web' => null,
                'nama_web' => null,
                'kode_ref' => null,
                'produk_nama' => 'HP SAMSUNG GALAXY Z FLIP 6 F741B 12/256GB - MINT',
                'available_stok' => 3,
                'merek_kode' => '1GA827285',
                'merek_nama' => 'SAMSUNG',
                'kategori_kode' => '12Z3J2847',
                'kategori_nama' => 'HP BARU',
                'sub_kategori_kode' => '1T6AE1905',
                'sub_kategori_nama' => 'HANDPHONE',
                'produk_satuan_kode' => '1100K2728',
                'produk_satuan_nama' => 'Unit',
                'produk_warna_kode' => '379LE0Y29',
                'produk_warna_nama' => 'MINT',
                'produk_ukuran_kode' => null,
                'produk_ukuran_nama' => null,
                'created_at' => Carbon::parse('2025-07-08 06:19:31'),
                'updated_at' => Carbon::parse('2025-07-08 06:19:31'),
            ],
            [
                'id' => 5,
                'kode' => '2E3OX190025',
                'nama' => 'HP IPHONE 16 PRO MAX 1TB RESMI',
                'slug' => 'hp-iphone-16-pro-max-1tb-resmi',
                'barcode' => '1726747094896',
                'harga_jual' => 32499000.00,
                'is_active' => 1,
                'is_jasa' => 0,
                'meta_keyword' => 'HP IPHONE 16 PRO MAX 1TB RESMI - BLACK TITANIUM',
                'meta_description' => 'HP IPHONE 16 PRO MAX 1TB RESMI - BLACK TITANIUM',
                'harga_diskon' => null,
                'deskripsi_produk' => null,
                'berat' => 1,
                'berat_pengiriman' => 1,
                'overview' => null,
                'is_paket' => 0,
                'harga_jual_web' => null,
                'harga_diskon_web' => null,
                'nama_web' => null,
                'kode_ref' => null,
                'produk_nama' => 'HP IPHONE 16 PRO MAX 1TB RESMI - BLACK TITANIUM',
                'available_stok' => 2,
                'merek_kode' => '1EYSP2728',
                'merek_nama' => 'APPLE',
                'kategori_kode' => '12Z3J2847',
                'kategori_nama' => 'HP BARU',
                'sub_kategori_kode' => '1T6AE1905',
                'sub_kategori_nama' => 'HANDPHONE',
                'produk_satuan_kode' => '1100K2728',
                'produk_satuan_nama' => 'Unit',
                'produk_warna_kode' => '415FPTK25',
                'produk_warna_nama' => 'BLACK TITANIUM',
                'produk_ukuran_kode' => null,
                'produk_ukuran_nama' => null,
                'created_at' => Carbon::parse('2025-07-08 06:19:31'),
                'updated_at' => Carbon::parse('2025-07-08 06:19:31'),
            ],
            [
                'id' => 6,
                'kode' => '24N1190025',
                'nama' => 'HP IPHONE 16 PRO MAX 1TB RESMI',
                'slug' => 'hp-iphone-16-pro-max-1tb-resmi-1',
                'barcode' => '1726747094905',
                'harga_jual' => 32499000.00,
                'is_active' => 1,
                'is_jasa' => 0,
                'meta_keyword' => 'HP IPHONE 16 PRO MAX 1TB - WHITE TITANIUM',
                'meta_description' => 'HP IPHONE 16 PRO MAX 1TB - WHITE TITANIUM',
                'harga_diskon' => 30499000.00,
                'deskripsi_produk' => null,
                'berat' => 1,
                'berat_pengiriman' => 1,
                'overview' => null,
                'is_paket' => 0,
                'harga_jual_web' => null,
                'harga_diskon_web' => null,
                'nama_web' => null,
                'kode_ref' => null,
                'produk_nama' => 'HP IPHONE 16 PRO MAX 1TB RESMI - WHITE TITANIUM',
                'available_stok' => 2,
                'merek_kode' => '1EYSP2728',
                'merek_nama' => 'APPLE',
                'kategori_kode' => '12Z3J2847',
                'kategori_nama' => 'HP BARU',
                'sub_kategori_kode' => '1T6AE1905',
                'sub_kategori_nama' => 'HANDPHONE',
                'produk_satuan_kode' => '1100K2728',
                'produk_satuan_nama' => 'Unit',
                'produk_warna_kode' => '414RJBB25',
                'produk_warna_nama' => 'WHITE TITANIUM',
                'produk_ukuran_kode' => null,
                'produk_ukuran_nama' => null,
                'created_at' => Carbon::parse('2025-07-08 06:19:31'),
                'updated_at' => Carbon::parse('2025-07-08 06:19:31'),
            ],
        ];

        $newData = [];

        // 2. Mapping Data
        foreach ($oldData as $item) {
            $newData[] = [
                // Mengambil field 'id' atau bisa juga 'kode' tergantung kebutuhan Anda
                'erzap_id'       => (string) $item['id'],
                'name'           => $item['nama'],
                'base_price'     => $item['harga_jual'],
                'discount_price' => $item['harga_diskon'],
                'stock'          => $item['available_stok'],
                'barcode'        => $item['barcode'],
                // Mengubah array item menjadi string JSON
                'raw_data'       => json_encode($item),
                'created_at'     => $item['created_at'],
                'updated_at'     => $item['updated_at'],
            ];
        }

        // 3. Insert ke Tabel Baru
        DB::table('product_erzaps')->insert($newData);

        $this->command->info('Data produk berhasil dimigrasikan ke tabel product_erzaps!');
    }
}
